#ifndef __DEBUG_LEDS_H
#define __DEBUG_LEDS_H

#include "stm32f3xx_hal.h"

#define DBG_LED1_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET)
#define DBG_LED1_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET)
#define DBG_LED1_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0)
#define DBG_LED2_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET)
#define DBG_LED2_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET)
#define DBG_LED2_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1)
#define DBG_LED3_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET)
#define DBG_LED3_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET)
#define DBG_LED3_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_3)

#endif