#ifndef __DEBUG_LEDS_H
#define __DEBUG_LEDS_H

#include "stm32f3xx_hal.h"

#define DBG_LED1_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_SET)
#define DBG_LED1_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, GPIO_PIN_RESET)
#define DBG_LED1_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0)
#define DBG_LED2_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET)
#define DBG_LED2_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_RESET)
#define DBG_LED2_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1)
#define DBG_LED3_ON() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_SET)
#define DBG_LED3_OFF() HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET)
#define DBG_LED3_TOGGLE() HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_3)

#define DBG_PIN1_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_SET)
#define DBG_PIN1_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PIN_RESET)
#define DBG_PIN1_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_0)

#define DBG_PIN2_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_SET)
#define DBG_PIN2_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_1, GPIO_PIN_RESET)
#define DBG_PIN2_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_1)

#define DBG_PIN3_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_SET)
#define DBG_PIN3_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, GPIO_PIN_RESET)
#define DBG_PIN3_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_6)

#define DBG_PIN4_ON() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_SET)
#define DBG_PIN4_OFF() HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, GPIO_PIN_RESET)
#define DBG_PIN4_TOGGLE() HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_7)

#define DBG_SR(__val) (__val ? GPIO_PIN_SET : GPIO_PIN_RESET)
#define DBG_EXT_WRITE(__WORD) do { \
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, DBG_SR(__WORD & 0B0001)); \
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, DBG_SR(__WORD & 0B0010)); \
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_6, DBG_SR(__WORD & 0B0100)); \
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_7, DBG_SR(__WORD & 0B1000)); \
} while (0U);



#endif